In [1]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64


[3 4 5 6]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
slice2=arr[::3]
slice3=arr[1:9:2]
print(slice1)
print(slice2)
print(slice3)

[3 4 5 6]
[1 4 7]
[2 4 6 8]


In [9]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:2,1:3]
print(substring)

[[2 3]
 [5 6]]


In [15]:
col1=arr[:,2]
print(col1)

[3 6 9]


In [19]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [18]:
print(arr[0:2:1])

[[1 2 3]
 [4 5 6]]


In [20]:
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
            

1


In [23]:
print(arr[1,2])

6


In [26]:
arr=[1,2,3,4,5,6]
print(arr[-1])

6


In [28]:
print(arr[2:5])


[3, 4, 5]


In [30]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[1:5])

[20 30 40 50]


In [2]:
#horizontal join:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
#VERTICAL JOINT:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
#DEPTH JOINT:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [10]:
#ARRAY SPLITTING:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.array_split(arr,4)
print(result)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
