In [1]:
import numpy as np
a=np.array((1,2,3))
print("one dimensional array:",a)

one dimensional array: [1 2 3]


In [2]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print("two dimensional array",a)

two dimensional array [[10 20 30]
 [40 50 60]]


In [4]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Three dimensional array",b)

Three dimensional array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros\n",c)


 Array with all zeros
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,2))
print("\nRandom value \n",d)


Random value 
 [[0.64838003 0.19705184]
 [0.88851519 0.65343068]
 [0.44339262 0.30563356]]


In [7]:
import numpy as np
e=np.arange(20,50,5)
print("\n Sequence array \n",e)


 Sequence array 
 [20 25 30 35 40 45]


In [10]:
import numpy as np
a=np.array(((1,2,3,4),(5,6,7,8),(9,10,11,12)))
b=a.reshape(4,3)
print("\n old array:\n",a)
print("\n reshaped array:\n",b)


 old array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat=arr.flatten()
print("Original array:\n",arr)
print("\n flatten array:\n",flat)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat=arr.flatten()
print("Original array:\n",arr)
print("\n flatten array:\n",flat)
print("\nNo of dimensions:",arr.ndim)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

No of dimensions: 2


In [25]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n array:",arr)
print("\n dimension:",arr.ndim)


 array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 dimension: 3


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

No of dimensions: 2


In [28]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat=arr.flatten()
print("\nNo of dimensions:",arr.ndim)
print("Shape of array:\n",arr.shape)


No of dimensions: 2
shape of array:
 (3, 4)


In [32]:
import numpy as np
arr=np.array(['a','b','c'])
a=np.array([1,2,3])

print("Length of array:",len(a))
print("Type of array:",arr.dtype)
print("Length of arrat:",len(arr))




Length of array: 3
Type of array: <U1
Length of arrat: 3


In [6]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]
